# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: example
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    networks:
      - intranet

networks:
  intranet:
    driver: bridge