# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb:10.9.2
    container_name: calendars-db
    environment:
      MARIADB_ROOT_PASSWORD: example
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    networks:
      - intranet
    volumes:
    # The :z is added due Selinux
      - ./data:/var/lib/mysql:z
  apache:
    image: httpd:2.4-alpine
    container_name: calendars-apache
    ports:
      - '8080:80'
    volumes:
    # The :z is added due Selinux
    - "../../frontend/dist/src:/usr/local/apache2/htdocs:z"
    networks:
      - intranet
  apache-mobile:
    image: httpd:2.4-alpine
    container_name: calendars-apache-mobile
    ports:
      - '8081:80'
    volumes:
    # The :z is added due Selinux
    - "../../mobile/dist/src:/usr/local/apache2/htdocs:z"
    networks:
      - intranet   

networks:
  intranet:
    driver: bridge