# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - 3306:3306
  adminer:
    image: adminer
    ports:
      - 8080:8080